#Docker file for General Spring Boot Exercise
FROM openjdk:8
RUN mkdir springapp
WORKDIR /springapp
ADD target/GeneralProgExec-0.0.1-SNAPSHOT.jar GeneralProgExec-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "GeneralProgExec-0.0.1-SNAPSHOT.jar"]
